site_name: BliKVM Handbook
docs_dir: '../../docs/en'
site_dir: '../../generated/en'
site_description: Open and cost-effective "KVM over IP". BliKVM comes in 3 different models, BliKVM PCIe, BliKVM HAT and BliKVM CM4, all based on Raspberry Pi.
site_author: Thomas Von
theme:
  name: material
  custom_dir: '../../overrides/'
  logo: assets/images/logo.png
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

extra:
  homepage: https://www.blicube.com
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ThomasVon2021/blikvm-site
      name: Join the translation work
  alternate:
    - name: English
      link: /blikvm/en/
      lang: en
    - name: 中文
      link: /blikvm/zh/
      lang: zh
repo_name: blikvm-site
repo_url: https://github.com/ThomasVon2021/blikvm-site
edit_uri: edit/master/docs/en/
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
    - "Getting Started":
        - "BLIKVM Overview": index.md
        - "BliKVM v4 Allwinner Guide": BliKVM-v4-guide.md
        - "BliKVM v3 HAT Guide": BLIKVM-HAT-guide.md
        - "BliKVM v2 PCIe Guide": BLIKVM-PCIE-guide.md
        - "BliKVM v1 CM4 Guide": BLIKVM-CM4-guide.md
        - "Multiport BliSwitch v1 (4-port)": bliswitch-v1-guide.md
        - "Multiport BliSwitch v2 (8-port)": bliswitch-v2-guide.md 
        - "First Steps": first_steps.md
        - "FAQ": faq.md
    - "Network":
        - "Internet Access":
            - "Port Forwarding": port-forwarding.md
            - "Tailscale VPN": tailscale.md
            - "ZeroTier VPN": zerotier.md
            - "WireGuard VPN": wireguard.md
            - "Cloudflare Tunnel": cloudflare-tunnels.md
        - "Set Static IP ": static_ip.md
        - "Wifi Config": wifi.md
        - "Encrypt certificates": https.md
    - "Video":
      - "Video modes": video-modes.md
      - "WebRTC configuration": webrtc.md
      - "HDMI EDID": edid.md
      - "HDMI passthrough": hdmi-passthrough.md
    - "Function":
        - "Upgrade": update.md
        - "Keyboard": hid.md
        - "RTC clock": rtc.md
        - "Flashing OS": flashing_os.md
        - "OLED Display": OLED-display.md
        - "Expand Filesystem": Expand_Filesystem.md
        - "Serial-over-USB": serial_over_usb.md 
        - "MSD": msd.md
        - "Wake-on-LAN": wake-on-lan.md
        - "SSH Terminal": ssh.md 
        - "security": security.md
    - "Installation Instructions":
        - "v3 HAT Illustrated Instructions": BLIHAT-Installation.md
        - "v2 PCIe Illustrated Instructions": BLIKVM-PCIe-installation.md
    - "Accessories":
        - "ATX Guide": atx-guide.md
        - "HDMI to CSI & Audio": hdmi-csi-i2s.md
        - "USB Splitter": usb-splitter-guide.md
    - "Development":
        - "Make Image": make-image.md
        - "Config for PiKVM OS": modify_pikvm_image.md
        - "v4 Allwinner Dev Guide": Dev-BliKVM-v4-Allwinner.md
        - "HTTP API": dev_api.md
plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  - search:
      lang: 
        - en
        - ja
        - ru
        - zh
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: DISABLE_PDF_EXPORT